from pydantic import BaseModel, Field
from typing import Optional, Literal
from datetime import datetime
from enum import Enum


class Team(Enum):
    HOME = "home"
    AWAY = "away"


class MatchStatus(Enum):
    NOT_STARTED = "not_started"
    FIRST_HALF = "first_half"
    HALFTIME = "halftime"
    SECOND_HALF = "second_half"
    FINISHED = "finished"


class GoalEvent(BaseModel):
    """Represents a goal scored during a match"""
    match_id: str
    timestamp: datetime
    minute: int
    team: Team
    scorer: Optional[str] = None
    home_score: int
    away_score: int
    
    @property
    def score_diff(self) -> int:
        """Positive = home leading, negative = away leading"""
        return self.home_score - self.away_score


class MatchInfo(BaseModel):
    """Basic match information"""
    match_id: str
    home_team: str
    away_team: str
    start_time: datetime
    league: str
    status: MatchStatus = MatchStatus.NOT_STARTED
    home_score: int = 0
    away_score: int = 0
    current_minute: int = 0


class MarketOutcome(BaseModel):
    """A single outcome in a Polymarket market"""
    token_id: str
    outcome: str  # e.g., "Yes", "No", "Home Win", "Draw", "Away Win"
    price: float  # 0-1
    
    @property
    def implied_probability(self) -> float:
        return self.price


class PolymarketMatch(BaseModel):
    """A Polymarket market for a soccer match"""
    market_id: str
    condition_id: str
    match_id: str  # External match ID from data provider
    question: str
    home_team: str
    away_team: str
    outcomes: list[MarketOutcome]
    end_date: datetime
    active: bool = True


class OrderSide(Enum):
    BUY = "BUY"
    SELL = "SELL"


class Order(BaseModel):
    """An order to place on Polymarket"""
    market_id: str
    token_id: str
    side: OrderSide
    size: float  # In USDC
    price: float  # Limit price (0-1)


class Position(BaseModel):
    """Current position in a market"""
    market_id: str
    token_id: str
    outcome: str
    size: float
    avg_price: float
    current_price: float
    unrealized_pnl: float


class TradeSignal(BaseModel):
    """Signal generated by the trading engine"""
    match_id: str
    market_id: str
    signal_type: Literal["entry", "exit"]
    side: OrderSide
    token_id: str
    recommended_size: float
    expected_edge: float
    reason: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
